### ISSUE TITLE
setCursor doesn't seem to be working.

### ISSUE THREAD

**Issue by lmorgan3d** [holgerlembke/st7567sfGK#2]
In using PlatformIO with an Arduino Nano for the st7567sfGK display: 
display.setCursor(0,1); 
display.println("Text");         does not put Text on the first line, Text goes to the bottom line of the display.  
Compiles fine, but setCursor not working.

**Comment by holgerlembke** [comment]
Thanks for the report.

After reviewing it, I came to the conclusion: Works as designed. :-)

The following grafic draws a line from 0/0 to 50/50 and writes the text at 5/20.

![grafik](https://github.com/holgerlembke/st7567sfGK/assets/2034993/c5e5a03c-12b7-42a0-a806-4638fd2fcc30)

The .setCursor() function sets the bottom left pixel position for the following print() command. I added a clarifying comment into the .h file.

I appreciate your comment, feel free to reopen it.

**Comment by lmorgan3d** [comment]
Hello Holger,
Thank you for the quick response.
The setCursor command that is used in the Arduino world is used to position
the cursor in order to format and present alpha/numeric data on the
display.
The command; setCursor(x,y); starts in the upper left hand corner,
increments in the X dir to the right, and increments in the Y axis down,
allowing format of the data screen.
The setCursor command thus allows you to position text anywhere on the
display starting in the upper left corner as being (0,0).

**Comment by holgerlembke** [comment]
Yes, standard might that be, but it depends on screen layout. I choose to use 0/0 bottom left.

https://github.com/holgerlembke/st7567sfGK/blob/49aa1aec85d4a5e18336408a1847484ec562a387/src/st7567sfGK.h#L11

I use 
```
display.rotatedisplay(true);
```
to have a print()-from-top-left-and-down-style display.

**Comment by lmorgan3d** [comment]
But printing text on a display is always top down, is there any way to
accomplish this?
You probably should not call the command setCursor as it does not allow you
to set the cursor anywhere in the display field.
